# Common properties
spring:
  profiles:
    active:
      - ${ACTIVE_PROFILE}
  banner:
    location: classpath:banner.txt
server:
  ssl:
    enabled: true
  port: ${PORT}
  servlet:
    context-path: "/request"
keycloak:
  auth-server-url: ${AUTH_URL}
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_CLIENT}
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET}
  use-resource-role-mappings: true
  bearer-only: true
  principal-attribute: email
  ssl-required: external
  confidential-port: 0
---
# dev H2 profile properties
spring:
  profiles: dev-h2
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:dev
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
---
# PROD profile properties
spring:
  profiles: dev-postgres

  datasource:
    password: postgres
    platform: postgres
    url: jdbc:postgresql://localhost:5432/od-request-dev
    username: postgres
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
---
# PROD profile properties
spring:
  profiles: prod

  datasource:
    platform: postgres
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: ${DATABASE_DDL_AUTO}
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

---
# TEST profile properties
spring:
  profiles: test

  datasource:
    password: postgres
    platform: postgres
    url: jdbc:postgresql://localhost:5432/od-request-test
    username: postgres